version: 3.0.0.{build}
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- ps: nuget restore src/I8Beef.Ecobee.sln
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
artifacts:
- path: src\I8Beef.Ecobee\bin\$(configuration)\netstandard2.0
  name: I8Beef.Ecobee-$(appveyor_build_version)
deploy:
- provider: NuGet
  api_key: $(NUGET_API_KEY)
  on:
    branch: release
- provider: GitHub
  auth_token: $(GITHUB_API_KEY)
  artifact: src\I8Beef.Ecobee\bin\$(configuration)\netstandard2.0\I8Beef.Ecobee-$(appveyor_build_version).zip
  on:
    branch: release